In [27]:
import numpy as np
import matplotlib as plt
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten

In [28]:
df = pd.read_csv('../data/Covid Data.csv')

In [29]:
df.shape

(1048575, 21)

In [30]:
df.head(40)

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97
5,2,1,1,2,9999-99-99,2,1,40,2,2,...,2,2,2,2,2,2,2,2,3,2
6,2,1,1,1,9999-99-99,97,2,64,2,2,...,2,2,2,2,2,2,2,2,3,97
7,2,1,1,1,9999-99-99,97,1,64,2,1,...,2,1,1,2,2,2,1,2,3,97
8,2,1,1,2,9999-99-99,2,2,37,2,1,...,2,2,1,2,2,1,2,2,3,2
9,2,1,1,2,9999-99-99,2,2,25,2,2,...,2,2,2,2,2,2,2,2,3,2
10,2,1,1,1,9999-99-99,97,2,38,2,2,...,2,2,2,2,2,2,2,2,3,97
11,2,1,2,2,9999-99-99,2,2,24,97,2,...,2,2,2,2,2,2,2,2,3,2
12,2,1,2,2,9999-99-99,2,2,30,97,2,...,2,2,2,2,2,2,2,2,3,2
13,2,1,2,1,9999-99-99,97,2,55,97,2,...,2,2,2,2,2,2,2,2,3,97
14,2,1,1,1,9999-99-99,97,2,48,2,1,...,2,2,2,2,2,2,2,2,3,97
15,2,1,1,1,9999-99-99,97,2,23,2,2,...,2,2,2,2,2,2,2,2,3,97
16,2,1,1,2,9999-99-99,2,1,80,2,2,...,2,2,1,2,2,2,2,2,3,1
17,2,1,2,1,9999-99-99,97,2,61,97,2,...,2,2,2,2,2,2,2,2,3,97
18,2,1,2,1,9999-99-99,97,2,54,97,2,...,2,2,2,2,2,2,2,2,3,97
19,2,1,1,1,9999-99-99,97,2,64,2,2,...,2,2,2,2,2,2,2,2,3,97
20,2,1,2,2,9999-99-99,2,1,59,97,1,...,2,2,2,2,2,2,2,1,3,1
21,2,1,2,1,9999-99-99,97,2,30,97,2,...,2,2,2,2,2,2,2,2,3,97
22,2,1,2,1,9999-99-99,97,2,45,97,2,...,2,2,2,2,2,2,2,2,3,97
23,2,1,1,1,9999-99-99,97,2,26,2,2,...,2,2,2,2,2,2,2,2,3,97
24,2,1,1,1,9999-99-99,97,2,38,2,2,...,2,2,2,2,2,2,1,2,3,97
25,2,1,2,1,9999-99-99,97,2,24,97,2,...,2,2,2,2,2,2,2,2,3,97
26,2,1,2,1,9999-99-99,97,2,32,97,2,...,2,2,2,2,2,2,2,2,3,97
27,2,1,2,1,9999-99-99,97,2,49,97,2,...,2,2,2,2,2,2,2,2,3,97
28,2,1,2,1,9999-99-99,97,2,39,97,2,...,2,2,2,2,2,2,2,1,3,97
29,2,1,2,1,9999-99-99,97,2,27,97,2,...,2,2,2,2,2,2,2,2,3,97
30,2,1,2,2,9999-99-99,2,1,45,97,2,...,2,2,2,2,2,2,2,2,3,2
31,2,1,1,1,9999-99-99,97,2,57,2,1,...,2,2,2,2,2,2,2,2,3,97
32,2,1,2,1,9999-99-99,97,2,25,97,2,...,2,2,2,2,2,2,2,2,3,97
33,2,1,2,1,9999-99-99,97,2,37,97,2,...,2,2,2,2,2,2,2,2,3,97
34,2,1,1,1,9999-99-99,97,2,49,2,2,...,2,2,2,2,2,2,2,2,3,97
35,2,1,2,1,9999-99-99,97,2,45,97,2,...,2,2,2,2,2,2,2,2,3,97
36,2,1,1,1,9999-99-99,97,2,20,2,2,...,2,2,2,2,2,2,2,2,3,97
37,2,1,1,1,9999-99-99,97,2,56,2,2,...,2,2,2,2,1,1,2,2,3,97
38,2,1,2,1,9999-99-99,97,2,47,97,2,...,1,2,2,1,1,2,2,2,3,97
39,2,1,1,1,9999-99-99,97,2,50,2,2,...,2,2,2,2,2,2,2,1,3,97

In [31]:
df.columns

Index(['USMER', 'MEDICAL_UNIT', 'SEX', 'PATIENT_TYPE', 'DATE_DIED', 'INTUBED',
       'PNEUMONIA', 'AGE', 'PREGNANT', 'DIABETES', 'COPD', 'ASTHMA', 'INMSUPR',
       'HIPERTENSION', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY',
       'RENAL_CHRONIC', 'TOBACCO', 'CLASIFFICATION_FINAL', 'ICU'],
      dtype='object')

In [32]:
df.head()

,USMER,MEDICAL_UNIT,SEX,PATIENT_TYPE,DATE_DIED,INTUBED,PNEUMONIA,AGE,PREGNANT,DIABETES,...,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,CLASIFFICATION_FINAL,ICU
0,2,1,1,1,03/05/2020,97,1,65,2,2,...,2,2,1,2,2,2,2,2,3,97
1,2,1,2,1,03/06/2020,97,1,72,97,2,...,2,2,1,2,2,1,1,2,5,97
2,2,1,2,2,09/06/2020,1,2,55,97,1,...,2,2,2,2,2,2,2,2,3,2
3,2,1,1,1,12/06/2020,97,2,53,2,2,...,2,2,2,2,2,2,2,2,7,97
4,2,1,2,1,21/06/2020,97,2,68,97,1,...,2,2,1,2,2,2,2,2,3,97

In [33]:
df['covid_status_binary'] = df['CLASIFFICATION_FINAL'].apply(
    lambda x: 1 if x in [1, 2, 3] else 0
)

In [34]:
df.drop(['INTUBED','PATIENT_TYPE','ICU','CLASIFFICATION_FINAL'], axis=1, inplace=True, errors='ignore')

In [35]:
df['died'] = df['DATE_DIED'].apply(lambda x: 0 if x == '9999-99-99' else 1)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 19 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   USMER                1048575 non-null  int64
 1   MEDICAL_UNIT         1048575 non-null  int64
 2   SEX                  1048575 non-null  int64
 3   DATE_DIED            1048575 non-null  object
 4   PNEUMONIA            1048575 non-null  int64
 5   AGE                  1048575 non-null  int64
 6   PREGNANT             1048575 non-null  int64
 7   DIABETES             1048575 non-null  int64
 8   COPD                 1048575 non-null  int64
 9   ASTHMA               1048575 non-null  int64
 10  INMSUPR              1048575 non-null  int64
 11  HIPERTENSION         1048575 non-null  int64
 12  OTHER_DISEASE        1048575 non-null  int64
 13  CARDIOVASCULAR       1048575 non-null  int64
 14  OBESITY              1048575 non-null  int64
 15  RENAL_CHRONIC        1048575 non-null  int64
 16  TOBACCO              1048575 non-null  int64
 17  covid_status_binary  1048575 non-null  int64
 18  died                 1048575 non-null  int64
dtypes: int64(18), object(1)
memory usage: 152.0+ MB

In [11]:
df.describe()

,USMER,MEDICAL_UNIT,SEX,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,covid_status_binary
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,1.632194e+00,8.980565e+00,1.499259e+00,3.346831e+00,4.179410e+01,4.976558e+01,2.186404e+00,2.260569e+00,2.242626e+00,2.298132e+00,2.128989e+00,2.435143e+00,2.261810e+00,2.125176e+00,2.257180e+00,2.214333e+00,3.738207e-01
std,4.822084e-01,3.723278e+00,4.999997e-01,1.191288e+01,1.690739e+01,4.751073e+01,5.424242e+00,5.132258e+00,5.114089e+00,5.462843e+00,5.236397e+00,6.646676e+00,5.194850e+00,5.175445e+00,5.135354e+00,5.323097e+00,4.838171e-01
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00
25%,1.000000e+00,4.000000e+00,1.000000e+00,2.000000e+00,3.000000e+01,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,0.000000e+00
50%,2.000000e+00,1.200000e+01,1.000000e+00,2.000000e+00,4.000000e+01,9.700000e+01,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,0.000000e+00
75%,2.000000e+00,1.200000e+01,2.000000e+00,2.000000e+00,5.300000e+01,9.700000e+01,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00
max,2.000000e+00,1.300000e+01,2.000000e+00,9.900000e+01,1.210000e+02,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,1.000000e+00

In [54]:
df.head(100)

,USMER,MEDICAL_UNIT,SEX,DATE_DIED,PNEUMONIA,AGE,PREGNANT,DIABETES,COPD,ASTHMA,INMSUPR,HIPERTENSION,OTHER_DISEASE,CARDIOVASCULAR,OBESITY,RENAL_CHRONIC,TOBACCO,covid_status_binary,died
0,2,1,1,03/05/2020,1,65,2,2,2,2,2,1,2,2,2,2,2,1,1
1,2,1,2,03/06/2020,1,72,0,2,2,2,2,1,2,2,1,1,2,0,1
2,2,1,2,09/06/2020,2,55,0,1,2,2,2,2,2,2,2,2,2,1,1
3,2,1,1,12/06/2020,2,53,2,2,2,2,2,2,2,2,2,2,2,0,1
4,2,1,2,21/06/2020,2,68,0,1,2,2,2,1,2,2,2,2,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,1,1,9999-99-99,2,49,2,2,2,2,2,2,2,2,2,2,2,0,0
96,2,1,1,9999-99-99,2,24,2,2,2,2,2,2,2,2,2,2,2,0,0
97,2,1,2,9999-99-99,2,28,0,2,2,2,2,2,2,2,2,2,2,0,0
98,2,1,2,9999-99-99,2,27,0,2,2,2,2,2,2,2,2,2,1,0,0
99,2,1,1,9999-99-99,2,26,2,2,2,2,2,2,2,2,2,2,1,0,0

In [38]:
cols_to_fix = ['PREGNANT']
df[cols_to_fix] = df[cols_to_fix].replace(97, 0)
df.shape

(1048575, 19)

In [55]:
y = df['died']
x = df.drop(['covid_status_binary','USMER','MEDICAL_UNIT','DATE_DIED'],axis=1)
y

0          1
1          1
2          1
3          1
4          1
          ..
1048570    0
1048571    0
1048572    0
1048573    0
1048574    0
Name: died, Length: 1048575, dtype: int64

In [40]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
output_X = scalar.fit_transform(x)

In [41]:
X_train, X_test, y_train, y_test = train_test_split(output_X, y, test_size=0.2,random_state = 1)

In [46]:
model = Sequential()
model.add(keras.Input(shape=(15,)))
model.add(Dense(7, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [47]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 7)              │           112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120 (480.00 B)

 Trainable params: 120 (480.00 B)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.compile(loss='binary_crossentropy',optimizer='Adam')

In [49]:
model.fit(X_train,y_train, epochs=2)

Epoch 1/2
26215/26215 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - loss: 0.0404
Epoch 2/2
26215/26215 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - loss: 2.6979e-09

In [50]:
model.layers[1].get_weights()

[array([[-1.637343 ],
        [-2.0562637],
        [-1.5530907],
        [-1.4623033],
        [-3.3619945],
        [ 4.101107 ],
        [-3.9340124]], dtype=float32),
 array([-0.15815853], dtype=float32)]

In [51]:
y_log = model.predict(X_test)

6554/6554 ━━━━━━━━━━━━━━━━━━━━ 6s 850us/step

In [52]:
y_pred= np.where(y_log>0.5,1,0)

In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

1.0